### ISSUE TITLE
🛑 API - Exchange Rates is down

### ISSUE THREAD

**Issue by toddspayde** [PuraVida-Technologies/pura-vida-status#17]
In [`66251a1`](https://github.com/PuraVida-Technologies/pura-vida-status/commit/66251a19b22d09058ecea956ad7136ed7fa34dbb
), API - Exchange Rates (https://api.puravidabitcoin.io/graphql) was **down**:
- HTTP code: 200
- Response time: 209 ms

**Comment by vmadman** [comment]
Deprecated
