### ISSUE TITLE
Add Twitter reporting to Upptime (if possible)

### ISSUE THREAD

**Issue by vmadman** [PuraVida-Technologies/pura-vida-status#5]
Depends On:
- https://github.com/PuraVida-Technologies/pura-vida-status/issues/3

---

Ideally, incident updates should automatically be reported to Twitter.

**Comment by toddspayde** [comment]
Twitter is not a supported alert target for Upptime. We would need to create a custom solution for this if we wanted to send status updates to Twitter.
